### ISSUE TITLE
It just does nothing

### ISSUE THREAD

**Issue by smoes** [n2o/clojure-lint-spacemacs-layer#1]
I followed your instructions precisely but it literally happens nothing.
messages-buffer tells me the layer is loaded correctly, but I see no effect at all. How can I verify it is loaded correctly?

I am using Emacs 26 with Spacemacs 200.13.x

**Comment by n2o** [comment]
Jeah, the first Issue :-)

Did you install `joker` and is it accessible in your path? This layer needs [joker](https://github.com/candid82/joker) on your machine.

**Comment by smoes** [comment]
There's always a first time ;) 

Yes, joker is fully accessible in my path.

**Comment by smoes** [comment]
I think the best way to start debugging would be to see if it is active/applied when opening a clojure file, at all. Is there a way to see if it is "activated"?

**Comment by n2o** [comment]
There was a problem with a version of joker. The developer announced, that upgrading joker and running it with the latest binary should work as expected:
https://github.com/candid82/flycheck-joker/commit/51e99e697761ee8dab863930910abdba7607c1bd

**Comment by n2o** [comment]
Updating to the latest versions of spacemacs, joker, all packages etc. fixed this problem for me. Please re-open if the error still persists.
